// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPortOpen(arg1, arg2) {
  return window['go']['app']['KnockHandler']['CheckPortOpen'](arg1, arg2);
}

export function CreateKnock(arg1) {
  return window['go']['app']['KnockHandler']['CreateKnock'](arg1);
}

export function DeleteKnock(arg1) {
  return window['go']['app']['KnockHandler']['DeleteKnock'](arg1);
}

export function KnockTarget(arg1, arg2) {
  return window['go']['app']['KnockHandler']['KnockTarget'](arg1, arg2);
}

export function ListKnocks() {
  return window['go']['app']['KnockHandler']['ListKnocks']();
}

export function UpdateKnock(arg1, arg2) {
  return window['go']['app']['KnockHandler']['UpdateKnock'](arg1, arg2);
}
