// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {knock} from '../models';

export function CheckPortOpen(arg1:knock.KnockData,arg2:string):Promise<boolean>;

export function CreateKnock(arg1:knock.KnockData):Promise<void>;

export function DeleteKnock(arg1:number):Promise<void>;

export function KnockTarget(arg1:knock.KnockData,arg2:string):Promise<void>;

export function ListKnocks():Promise<Array<knock.KnockData>>;

export function UpdateKnock(arg1:number,arg2:knock.KnockData):Promise<void>;
