// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildMigrationURI(arg1) {
  return window['go']['app']['TOTPHandler']['BuildMigrationURI'](arg1);
}

export function DeleteTOTP(arg1) {
  return window['go']['app']['TOTPHandler']['DeleteTOTP'](arg1);
}

export function GenerateTOTP(arg1) {
  return window['go']['app']['TOTPHandler']['GenerateTOTP'](arg1);
}

export function GetCurrentCode(arg1) {
  return window['go']['app']['TOTPHandler']['GetCurrentCode'](arg1);
}

export function ImportTOTP(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['TOTPHandler']['ImportTOTP'](arg1, arg2, arg3, arg4, arg5);
}

export function ListTOTPs() {
  return window['go']['app']['TOTPHandler']['ListTOTPs']();
}

export function ParseMigrationURI(arg1) {
  return window['go']['app']['TOTPHandler']['ParseMigrationURI'](arg1);
}

export function UpdateTOTP(arg1, arg2) {
  return window['go']['app']['TOTPHandler']['UpdateTOTP'](arg1, arg2);
}
