// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {totp} from '../models';

export function BuildMigrationURI(arg1:Array<totp.TOTPData>):Promise<string>;

export function DeleteTOTP(arg1:number):Promise<void>;

export function GenerateTOTP(arg1:totp.GenerateTOTPRequest):Promise<totp.TOTPData>;

export function GetCurrentCode(arg1:string):Promise<string>;

export function ImportTOTP(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ListTOTPs():Promise<Array<totp.TOTPData>>;

export function ParseMigrationURI(arg1:string):Promise<Array<totp.TOTPData>>;

export function UpdateTOTP(arg1:number,arg2:totp.TOTPData):Promise<void>;
